[tool.poetry]
name = "tokenization"
version = "0.1.0"
description = ""
authors = ["Christian Batista <me@christianbatista.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
